In [13]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("sample_submission.csv")
df

       ImageId  Label
0            1      0
1            2      0
2            3      0
3            4      0
4            5      0
...        ...    ...
27995    27996      0
27996    27997      0
27997    27998      0
27998    27999      0
27999    28000      0

[28000 rows x 2 columns]

In [4]:
train = pd.read_csv("train.csv")
train

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
test = pd.read_csv("test.csv")
test

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D
from keras.optimizers import RMSprop
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ReduceLROnPlateau, CSVLogger

In [7]:
import tensorflow as tf

In [8]:
train1=train.drop(columns=['label']).to_numpy().reshape((-1,28,28,1))/255
label=train['label'].to_numpy()
test=test.to_numpy().reshape((-1,28,28,1))/255

In [9]:
datagen =tf.keras.preprocessing.image.ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=10,  # randomly rotate images in the range (degrees, 0 to 180)
        zoom_range = 0.1, # Randomly zoom image 
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=False,  # randomly flip images
        vertical_flip=False)  # randomly flip images


datagen.fit(train1)

In [10]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(32,kernel_size=(3,3),input_shape=(28,28,1),use_bias=True,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Conv2D(128,kernel_size=(4,4),use_bias=True,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2),strides=(2,2)))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Conv2D(256,kernel_size=(4,4),use_bias=True,activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2)))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(32,activation='relu'))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [11]:
model.fit(train1,label,epochs=30)

Epoch 1/30
1313/1313 [==============================] - 148s 111ms/step - loss: 0.1961 - accuracy: 0.9490
Epoch 2/30
1313/1313 [==============================] - 156s 118ms/step - loss: 0.0611 - accuracy: 0.9805
Epoch 3/30
1313/1313 [==============================] - 151s 115ms/step - loss: 0.0465 - accuracy: 0.9855
Epoch 4/30
1313/1313 [==============================] - 147s 112ms/step - loss: 0.0384 - accuracy: 0.9885
Epoch 5/30
1313/1313 [==============================] - 150s 115ms/step - loss: 0.0321 - accuracy: 0.9900
Epoch 6/30
1313/1313 [==============================] - 160s 122ms/step - loss: 0.0281 - accuracy: 0.9913
Epoch 7/30
1313/1313 [==============================] - 153s 116ms/step - loss: 0.0255 - accuracy: 0.9927
Epoch 8/30
1313/1313 [==============================] - 149s 114ms/step - loss: 0.0235 - accuracy: 0.9922
Epoch 9/30
1313/1313 [==============================] - 147s 112ms/step - loss: 0.0195 - accuracy: 0.9940
Epoch 10/30
1313/1313 [==============================] - 150s 114ms/step - loss: 0.0172 - accuracy: 0.9946
Epoch 11/30
1313/1313 [==============================] - 145s 110ms/step - loss: 0.0193 - accuracy: 0.9938
Epoch 12/30
1313/1313 [==============================] - 145s 111ms/step - loss: 0.0154 - accuracy: 0.9953
Epoch 13/30
1313/1313 [==============================] - 148s 112ms/step - loss: 0.0145 - accuracy: 0.9957
Epoch 14/30
1313/1313 [==============================] - 148s 112ms/step - loss: 0.0139 - accuracy: 0.9956
Epoch 15/30
1313/1313 [==============================] - 168s 128ms/step - loss: 0.0103 - accuracy: 0.9969
Epoch 16/30
1313/1313 [==============================] - 150s 114ms/step - loss: 0.0133 - accuracy: 0.9957
Epoch 17/30
1313/1313 [==============================] - 143s 109ms/step - loss: 0.0108 - accuracy: 0.9965
Epoch 18/30
1313/1313 [==============================] - 142s 108ms/step - loss: 0.0101 - accuracy: 0.9966
Epoch 19/30
1313/1313 [==============================] - 144s 110ms/step - loss: 0.0114 - accuracy: 0.9964
Epoch 20/30
1313/1313 [==============================] - 145s 110ms/step - loss: 0.0093 - accuracy: 0.9970
Epoch 21/30
1313/1313 [==============================] - 145s 111ms/step - loss: 0.0088 - accuracy: 0.9972
Epoch 22/30
1313/1313 [==============================] - 146s 111ms/step - loss: 0.0092 - accuracy: 0.9970
Epoch 23/30
1313/1313 [==============================] - 145s 110ms/step - loss: 0.0101 - accuracy: 0.9968
Epoch 24/30
1313/1313 [==============================] - 150s 114ms/step - loss: 0.0069 - accuracy: 0.9978
Epoch 25/30
1313/1313 [==============================] - 161s 123ms/step - loss: 0.0062 - accuracy: 0.9982
Epoch 26/30
1313/1313 [==============================] - 137s 105ms/step - loss: 0.0085 - accuracy: 0.9973
Epoch 27/30
1313/1313 [==============================] - 143s 109ms/step - loss: 0.0063 - accuracy: 0.9980
Epoch 28/30
1313/1313 [==============================] - 148s 113ms/step - loss: 0.0061 - accuracy: 0.9980
Epoch 29/30
1313/1313 [==============================] - 146s 111ms/step - loss: 0.0062 - accuracy: 0.9980
Epoch 30/30
1313/1313 [==============================] - 151s 115ms/step - loss: 0.0071 - accuracy: 0.9978

In [14]:
result=model.predict(test)
ans=np.argmax(result,axis=1)
answer=pd.read_csv('sample_submission.csv')
answer['Label']=ans
ans=np.argmax(result,axis=1)
answer.index=answer['ImageId']
answer.drop(columns=['ImageId']).to_csv('answer.csv')

875/875 [==============================] - 14s 16ms/step

In [15]:
ans = pd.read_csv("answer.csv")
ans

       ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      0
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [17]:
ss = pd.read_csv("test.csv")
ss

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
!kaggle competitions submit digit-recognizer -f answer.csv -m "Latest Submission"

In [ ]:
!kaggle competitions submissions digit-recognizer

In [ ]:
from tensorflow.keras.models import load_model

model.save('my_model.h5') 

model = load_model('my_model.h5')